# Generated by Django 4.2.6 on 2024-02-07 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_loss', models.IntegerField(blank=True, null=True)),
                ('take_profit', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('dollar_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('usdt_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('btc_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('xlm_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('eth_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('usdc_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('xrp_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('doge_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('bnb_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('sol_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('ada_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
