# Generated by Django 4.2.6 on 2024-02-10 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_trade_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='images/proof'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deposit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
