# Generated by Django 4.2.6 on 2024-02-10 17:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deposit_amount_deposit_created_deposit_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
