# Generated by Django 4.2.6 on 2024-02-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_deposit_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
