# Generated by Django 4.2.6 on 2024-03-21 18:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_deposit_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('win_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('wins', models.CharField(blank=True, max_length=200, null=True)),
                ('losses', models.CharField(blank=True, max_length=200, null=True)),
                ('profit_share', models.CharField(blank=True, max_length=200, null=True)),
                ('copy_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
