# Generated by Django 4.2.6 on 2024-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_copytrader'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_wallets',
            name='ticker_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
