# Generated by Django 4.2.6 on 2024-03-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_deposit_wallets_ticker_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='proof',
        ),
    ]
