# Generated by Django 4.2.6 on 2024-03-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_deposit_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='expert_trade',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
